Repository DMSport/DMSport-Server, pull requests merged in 2022-10, with the labels that each got.

#28 🔀 :: (#25) 스포츠 클럽 엔티티 생성
  src/main/java/com/project/dmsport/domain/club/domain/Club.java
  src/main/java/com/project/dmsport/domain/club/domain/enums/ClubType.java
  src/main/java/com/project/dmsport/domain/club/domain/repository/ClubRepository.java
Labels: 기능추가

#30 🔀 :: (#29) 투표, 투표 유저 엔티티 생성
  src/main/java/com/project/dmsport/domain/vote/domain/Vote.java
  src/main/java/com/project/dmsport/domain/vote/domain/VoteUser.java
  src/main/java/com/project/dmsport/domain/vote/domain/VoteUserId.java
  src/main/java/com/project/dmsport/domain/vote/domain/enums/VoteType.java
  src/main/java/com/project/dmsport/domain/vote/domain/repository/VoteRepository.java
  src/main/java/com/project/dmsport/domain/vote/domain/repository/VoteUserRepository.java
Labels: 기능추가

#34 🔀 :: (#32) 클럽매니저 엔티티 생성
  src/main/java/com/project/dmsport/domain/club/domain/Club.java
  src/main/java/com/project/dmsport/domain/club/domain/ClubManager.java
  src/main/java/com/project/dmsport/domain/club/domain/repository/ClubManagerRepository.java
  src/main/java/com/project/dmsport/domain/vote/domain/Vote.java
Labels: 기능추가

#47 🔀 :: (#45) 클럽장 변경 API
  src/main/java/com/project/dmsport/domain/admin/service/ChangeClubManagerService.java
  src/main/java/com/project/dmsport/domain/admin/service/QueryUserListService.java
  src/main/java/com/project/dmsport/domain/user/domain/User.java
Labels: 리팩토링

#59 🔀 :: (#58) 투표 리스트 가져올 때 에러
  src/main/java/com/project/dmsport/domain/club/domain/repository/ClubRepository.java
  src/main/java/com/project/dmsport/domain/vote/domain/repository/VoteRepository.java
  src/main/java/com/project/dmsport/domain/vote/scheduler/CloseVoteScheduler.java
  src/main/java/com/project/dmsport/domain/vote/scheduler/VoteScheduler.java
Labels: 버그

#72 🔀 :: (#71) TokenResponse에 Authority 추가
  src/main/java/com/project/dmsport/domain/auth/presentation/dto/response/TokenResponse.java
  src/main/java/com/project/dmsport/domain/notice/presentation/dto/response/QueryAllNoticesResponse.java
  src/main/java/com/project/dmsport/domain/notice/service/QueryAllNoticesService.java
  src/main/java/com/project/dmsport/domain/user/service/LoginService.java
  src/main/java/com/project/dmsport/domain/user/service/SignupService.java
Labels: 기능추가
